<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Name>InputTools</Name>
    <Description>Tools to simplify inputs from keyboard, mouse and controller.</Description>
    <MinimumApiVersion>4.5.2</MinimumApiVersion>
    <UpdateKeys>Nexus:14553</UpdateKeys>
    <Version>0.2.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <EnableHarmony>true</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.4.1" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

</Project>
